import re



def jamshed(hadith):


  hadith = str(hadith)

  
  hadith = re.sub("'Muhammad", "Muḥammad", hadith)
  hadith = re.sub("Muhammad", "Muḥammad", hadith)
  hadith = re.sub("Muhammed", "Muḥammad", hadith)
  hadith = re.sub("Mohammad", "Muḥammad", hadith)
  hadith = re.sub("Muhammed", "Muḥammad", hadith)
  hadith = re.sub("Muhammad,", "Muḥammad,", hadith)
  hadith = re.sub("“(Muhammad),", "“(Muḥammad),", hadith)
  hadith = re.sub("(Muhammad),", "(Muḥammad),", hadith)

  
  hadith = re.sub("(Muhammad)", "(Muḥammad)", hadith)
  hadith = re.sub("Muhammad.", "Muḥammad.", hadith)

  

  
  hadith = re.sub("Abu", "Abū", hadith)
  hadith = re.sub("abu", "Abū", hadith)
  hadith = re.sub("“Abu", "“Abū", hadith)
  hadith = re.sub("“abu", "“Abū", hadith)
  #hadith = re.sub("(abu", "(Abū", hadith)
  hadith = re.sub("Allah", "Allāh", hadith)
  hadith = re.sub("Allah?”", "Allāh?”", hadith)
  hadith = re.sub("“Allah", "“Allāh", hadith)
  hadith = re.sub("Allah.”", "Allāh.”", hadith)
  hadith = re.sub("“Allah", "“Allāh", hadith)
  hadith = re.sub("Allah’s", "Allāh's", hadith)
  #hadith = re.sub("Allah)", "Allāh)", hadith)
  #hadith = re.sub("‘Allah", "Allāh)", hadith)
  hadith = re.sub("‘Ali", "ʿAlī", hadith)
  hadith = re.sub("Ali’s", "ʿAlī's", hadith)
  hadith = re.sub("Ali", "ʿAlī", hadith)
  #hadith = re.sub("(Ali", "(ʿAlī", hadith)
  hadith = re.sub("“Ali", "“ʿAlī", hadith)
  hadith = re.sub("'Ali,", "ʿAlī,", hadith)
  hadith = re.sub("'Ali.", "ʿAlī.", hadith)
  hadith = re.sub("Abul ", "Abū l-", hadith)
  hadith = re.sub("Ahmad", "Aḥmad", hadith)
  hadith = re.sub("Ahmed", "Aḥmad", hadith)
  hadith = re.sub("al-Hasan", "al-Ḥasan", hadith)
  hadith = re.sub("al-Hassan,", "al-Ḥasan", hadith)
  hadith = re.sub("Hasan", "Ḥasan", hadith)
  hadith = re.sub("Hassa’n", "Ḥasan", hadith)
  hadith = re.sub("al-Hassan", "al-Ḥasan", hadith)
  hadith = re.sub("Hassan", "Ḥasan", hadith)
  hadith = re.sub("'Abdillah'", "ʿAbd Allāh", hadith)
  hadith = re.sub("Abdillah'", "ʿAbd Allāh", hadith)
  hadith = re.sub("Abdullah", "ʿAbd Allāh", hadith)
  hadith = re.sub("‘Abdullah", "ʿAbd Allāh", hadith)
  hadith = re.sub("‘Abdallah", "ʿAbd Allāh", hadith)
  hadith = re.sub("Abdallah", "ʿAbd Allāh", hadith)
  hadith = re.sub("’Abdallah", "ʿAbd Allāh", hadith)
  hadith = re.sub("‘Abdallah,", "ʿAbd Allāh,", hadith)
  hadith = re.sub("Abi", "ʿAbī", hadith)
  hadith = re.sub("Amirul", "ʾAmīr al", hadith)
  hadith = re.sub("Amir", "ʾAmīr", hadith)
  hadith = re.sub("‘Amir", "ʾAmīr", hadith)
  hadith = re.sub("“Amir", "“ʾAmīr", hadith)
  hadith = re.sub("al-Mu’minin", "al-Muʾminīn", hadith)
  hadith = re.sub("Amir-ul-Momineen", "ʾAmīr al-Muʾminīn", hadith)
  hadith = re.sub("the commander of the faithful", "ʾAmīr al-Muʾminīn", hadith)
  hadith = re.sub("Momineen", "Muʾminīn", hadith)
  hadith = re.sub("al-Husayn", "al-Ḥusayn", hadith)
  hadith = re.sub("Husayn", "Ḥusayn", hadith)
  hadith = re.sub("Hussein", "Ḥusayn", hadith)
  hadith = re.sub("al-Hussein", "al-Ḥusayn", hadith)
  hadith = re.sub("imam", "Imām", hadith)
  hadith = re.sub("Imam?”", "Imām?”", hadith)
  #hadith = re.sub("'Imam)", "Imām)", hadith)
  hadith = re.sub("Imam", "Imām", hadith)
  hadith = re.sub("Imam,", "Imām", hadith)
  #hadith = re.sub("“(Imam)", "“(Imām)", hadith)
  hadith = re.sub("“Imam", "“Imām", hadith)
  #hadith = re.sub("(Imam)", "(Imām)", hadith)
  #hadith = re.sub("(Imam", "(Imām", hadith)
  hadith = re.sub("Imam.", "Imām.", hadith)
  hadith = re.sub("Imam.”", "Imām.”", hadith)
  hadith = re.sub("Imams", "Imāms", hadith)
  hadith = re.sub("Imams.", "Imāms.", hadith)
  hadith = re.sub("ibn", "b.", hadith)
  hadith = re.sub("Ibn", "b.", hadith)
  hadith = re.sub("bin", "b.", hadith)
  hadith = re.sub("Bin", "b.", hadith)
  hadith = re.sub("Yahya", "Yahyā", hadith)
  hadith = re.sub("Ibrahim", "Ibrāhīm", hadith)
  hadith = re.sub("Abraham", "Ibrāhīm", hadith)
  hadith = re.sub("Musa", "Mūsā", hadith)
  hadith = re.sub("Moses", "Mūsā", hadith)
  hadith = re.sub("Mu‘alla", "Muʿallā", hadith)
  hadith = re.sub("Ziyad", "Ziyād", hadith)
  hadith = re.sub("Hisham", "Hishām", hadith)
  hadith = re.sub("Hisham,", "Hishām", hadith)
  hadith = re.sub("al-Rida", "al-Riḍā", hadith)
  hadith = re.sub("Yunus", "Yūnus", hadith)
  hadith = re.sub("Quran", "Qurʾān", hadith)
  hadith = re.sub("Qur’an", "Qurʾān", hadith)
  hadith = re.sub("Quran.", "Qurʾān.", hadith)
  hadith = re.sub("Quran.”", "Qurʾān.”", hadith)
  hadith = re.sub("Quran,", "Qurʾān,", hadith)
  #hadith = re.sub("Quran)", "Qurʾān)", hadith)
  hadith = re.sub("Hadith", "Ḥadīth", hadith)
  hadith = re.sub("Hadith.", "Ḥadīth.", hadith)
  hadith = re.sub("hadith.", "hadīth.", hadith)
  hadith = re.sub("Khalid", "Khālid", hadith)
  hadith = re.sub("Sinan", "Sinān", hadith)
  hadith = re.sub("Mahbub", "Maḥbub", hadith)
  hadith = re.sub("al-Hakam", "al-Ḥakam", hadith)
  hadith = re.sub("Ishaq", "Isḥāq", hadith)
  hadith = hadith.replace("(a.s.).", "(ع)")
  hadith = hadith.replace("(a.s.).", "(ع)")
  hadith = hadith.replace("(a.s.)", "(ع)")
  hadith = hadith.replace("(a.s.)?”", "(ع)?”")
  hadith = hadith.replace("(a.s.)?", "(ع)?")
  hadith = hadith.replace("(a.s)", "(ع)")
  hadith = hadith.replace("(as)", "(ع)")
  hadith = hadith.replace("(A.S.)", "(ع)")
  hadith = hadith.replace("(MGB)", "(ع)")
  hadith = hadith.replace("(asws)", "(ع)")
  hadith = hadith.replace("(AS)", "(ع)")
  hadith = hadith.replace("(a)", "(ع)")
  hadith = hadith.replace("(A)", "(ع)")
  hadith = hadith.replace("(RA)", "(ر)")
  hadith = hadith.replace("(r)", "(ر)")
  hadith = hadith.replace("(rh)", "(ر)")
  hadith = hadith.replace("(A.S.)", "(ع)")
  hadith = re.sub("‘Alayhi al-Salam", "(ع)", hadith)
  hadith = re.sub("‘Alayhim al-Salam", "(ع)", hadith)
  hadith = hadith.replace(", (ع),", " (ع),")
  hadith = hadith.replace(", (ر),", " (ر),")

  
  hadith = hadith.replace("(azwj)", "(س)")
  
  
  hadith = re.sub("al-Barqiy", "al-Barqī", hadith)
  hadith = re.sub("Basir", "Baṣīr", hadith)
  hadith = re.sub("Hamza", "Ḥamza", hadith)
  hadith = re.sub("Hamzah", "Ḥamza", hadith)
  hadith = re.sub("Hammad", "Ḥammad", hadith)
  hadith = re.sub("Talib", "Ṭālib", hadith)
  hadith = re.sub("al-Rahman", "al-Raḥmān", hadith)
  hadith = re.sub("al-Qasim", "al-Qāsim", hadith)
  hadith = re.sub("Wilaya", "Wilāya", hadith)
  hadith = hadith.replace("(saw)", "(ص)")
  hadith = hadith.replace("(s.a.).", "(ص)")
  hadith = hadith.replace("(s.a.)", "(ص)")
  hadith = hadith.replace("(s.a)", "(ص)")
  hadith = hadith.replace("(sa)", "(ص)")
  hadith = hadith.replace("(s.a).", "(ص)")
  hadith = hadith.replace("(s.a).”", "(ص)”")
  hadith = hadith.replace("(s)", "(ص)")


  hadith = hadith.replace(", (ص),", " (ص),")
  hadith = re.sub("Jibril", "Jibrīl", hadith)
  hadith = re.sub("“Jibril", "“Jibrīl", hadith)
  hadith = re.sub("Yazid", "Yazīd", hadith)
  hadith = re.sub("Fatima", "Fāṭima", hadith)
  hadith = re.sub("Fatima,", "Fāṭima,", hadith)
  hadith = re.sub("Salih", "Ṣāliḥ", hadith)
  hadith = re.sub("’Isma‘il", "ʾIsmaʿīl", hadith)
  hadith = re.sub("Isma‘il", "ʾIsmaʿīl", hadith)
  hadith = re.sub("‘Uthman", "ʿUthmān", hadith)
  hadith = re.sub("Jabir", "Jābir", hadith)
  hadith = re.sub("Imamat", "Imāmah", hadith)
  hadith = re.sub("Safwan", "Ṣafwān", hadith)
  hadith = re.sub("Sulayman", "Sulaymān", hadith)
  hadith = re.sub("Solomon", "Sulaymān", hadith)
  hadith = re.sub("Ayyub", "Ayyūb", hadith)
  hadith = re.sub("Salim", "Sālim", hadith)
  hadith = re.sub("Hashim", "Manṣūr", hadith)
  hadith = re.sub("Mansur", "Jibrīl", hadith)
  hadith = re.sub("Idris", "ʾIdris", hadith)
  hadith = re.sub("Aban", "ʾAbān", hadith)
  hadith = re.sub("al-Mahdi‘", "al-Mahdi", hadith)
  hadith = re.sub("Dawud", "Dāwūd", hadith)
  hadith = re.sub("David", "Dāwūd", hadith)
  hadith = re.sub("Nasr", "Naṣr", hadith)
  hadith = re.sub("Adam", "Ādam", hadith)
  hadith = re.sub("Hajj", "Ḥajj", hadith)
  hadith = re.sub("Zurara", "Zurāraʿ", hadith)
  hadith = re.sub("Zurarah", "Zurāraʿ", hadith)
  hadith = re.sub("al-Fadl", "al-Faḍl", hadith)
  hadith = re.sub("Jumhur", "Jumhūr", hadith)
  hadith = re.sub("al-Fudayl", "al-Fuḍayl", hadith)
  hadith = re.sub("Shi‘a", "Shīʿa", hadith)
  hadith = re.sub("‘Ammar", "ʿAmmār", hadith)
  hadith = re.sub("Ammar", "ʿAmmār", hadith)
  hadith = re.sub("’Isa", "ʿĪsa", hadith)
  hadith = re.sub("Esa", "ʿĪsa", hadith)
  hadith = re.sub("Jesus‘", "ʿĪsa", hadith)
  hadith = re.sub("al-Ash‘ari", "al-Ashʿarī", hadith)
  hadith = re.sub("Faddal", "Faḍḍāl", hadith)
  hadith = re.sub("Mu‘awiya", "Muʿāwīya", hadith)
  hadith = re.sub("al-Jabbar", "al-Jabbār", hadith)
  hadith = re.sub("Satan", "Shaytan", hadith)
  hadith = re.sub("al-Mufaddal", "al-Mufaḍḍal", hadith)
  hadith = re.sub("Mufaddal", "Mufaḍḍal", hadith)
  hadith = re.sub("al-Muttalib", "al-Muṭṭalib", hadith)
  hadith = re.sub("al-Halabi", "al-Ḥalabī", hadith)
  hadith = re.sub("Shadhan", "Shādhān", hadith)
  hadith = re.sub("Fudayl", "Fuḍayl", hadith)
  hadith = re.sub("Kathir", "Kathīr", hadith)
  hadith = re.sub("Al-Qa’im", "al-Qāʾim", hadith)
  hadith = re.sub("Mary", "Maryam", hadith)
  hadith = re.sub("al-‘Abbass", "al-ʿAbbās", hadith)
  hadith = re.sub("‘Abbass", "ʿAbbās", hadith)
  hadith = re.sub("‘Imran", "ʿImrān", hadith)
  hadith = re.sub("Maymun", "Maymūn", hadith)
  hadith = re.sub("al-Ja‘fari", "al-Jaʿfarī", hadith)
  hadith = re.sub("Ya‘qub", "Ya'qūb", hadith)
  hadith = re.sub("Ya’qub", "Ya'qūb", hadith)
  hadith = re.sub("ya‘qub", "Ya'qūb", hadith)
  hadith = re.sub("Marwan", "Marwān", hadith)
  hadith = re.sub("Humran", "Ḥumrān", hadith)
  hadith = re.sub("Mahziyar", "Mahziyār", hadith)
  hadith = re.sub("al-‘Azim", "al-ʿAẓīm", hadith)
  hadith = re.sub("al-‘Aziz", "al-ʿAzīz", hadith)
  hadith = re.sub("al-Mukhtar", "al-Mukhtār", hadith)
  hadith = re.sub("Baghdad", "Baghdād ", hadith)
  hadith = re.sub("al-Hamid", "al-Ḥārith", hadith)
  hadith = re.sub("al-Mu’minin", "al-Muʾminīn", hadith)
  hadith = re.sub("al-Khattab", "al-Khaṭṭāb", hadith)
  hadith = re.sub("‘Abdal", "ʿAbd al", hadith)
  hadith = re.sub("al-Walid", "al-Walīd", hadith)
  hadith = re.sub("Hariz", "ʿĀṣim", hadith)
  hadith = re.sub("‘Asim", "Islām", hadith)
  hadith = re.sub("Rashid", "Rāshid", hadith)
  hadith = re.sub("al-Sindi", "al-Sindī", hadith)
  hadith = re.sub("al-Hassani", "al-Ḥasanī", hadith)
  hadith = re.sub("Kufa", "Kūfa", hadith)
  hadith = re.sub("Al-Ma’mun", "al-Maʾmūn", hadith)
  hadith = re.sub("al-Ma’mun", "al-Maʾmūn", hadith)
  hadith = re.sub("Ya‘fur", "Yaʿfūr", hadith)
  hadith = re.sub("Najran", "Najrān", hadith)
  hadith = re.sub("al-‘Ijli", "al-ʿIjlī", hadith)
  hadith = re.sub("al-Kufi", "al-Kūfī", hadith)
  hadith = re.sub("Yasar", "Yasār", hadith)
  hadith = re.sub("Yasir", "Yasār", hadith)
  hadith = re.sub("al-‘Alawi", "al-ʿAlawī", hadith)
  hadith = re.sub("al-Yamani", "al-Yamān", hadith)
  hadith = re.sub("Surah", "Sūra", hadith)
  hadith = re.sub("Khadija", "Khadīja", hadith)
  hadith = re.sub("Sufyan", "Sufyān", hadith)
  hadith = re.sub("al-‘Attar", "al-ʿAṭṭār", hadith)
  hadith = re.sub("Hakim", "Ḥakīm", hadith)
  hadith = re.sub("Mawla", "Mawlā", hadith)
  hadith = re.sub("Mu’minin", "Muʾminīn", hadith)
  hadith = re.sub("Yaqtin", "Yaqtīn", hadith)
  hadith = re.sub("al-Jarud", "al-Jārūd", hadith)
  hadith = re.sub("al-Nawfali", "Islām", hadith)
  hadith = re.sub("Islam", "Islām", hadith)
  
  
  
  

  

  return hadith
